# Generated by Django 5.2 on 2025-04-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('EDUCATOR', 'Educator'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10),
        ),
    ]
