# Generated by Django 5.2 on 2025-05-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_userprogress_options_alter_userprogress_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentupload',
            name='content_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentupload',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
