# Generated by Django 5.2 on 2025-05-09 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_topic_formatted_content_topic_raw_content_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=50, unique=True)),
                ('text', models.TextField()),
                ('domain', models.CharField(choices=[('algebra', 'Algebra'), ('geometry', 'Geometry'), ('trigonometry', 'Trigonometry'), ('calculus', 'Calculus'), ('statistics', 'Statistics')], max_length=50)),
                ('grade_level', models.CharField(choices=[('8th', '8th Grade'), ('9th', '9th Grade'), ('10th', '10th Grade'), ('11th', '11th Grade'), ('12th', '12th Grade')], max_length=10)),
                ('concepts', models.JSONField(default=list)),
                ('correct_answer', models.TextField()),
                ('correct_workings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='correct_workings',
            field=models.JSONField(default=list, help_text='List of correct working steps'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('8th', '8th Grade'), ('9th', '9th Grade'), ('10th', '10th Grade'), ('11th', '11th Grade'), ('12th', '12th Grade')], default='10th', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='math_concepts',
            field=models.JSONField(default=list, help_text='List of math concepts tested'),
        ),
        migrations.CreateModel(
            name='MathWorkings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.JSONField(default=list)),
                ('answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('error_types', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workings', to='backend.mathproblem')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Math Workings',
            },
        ),
    ]
